lib/simple_email_list_web/router.ex
defmodule SimpleEmailListWeb.Router do
  use SimpleEmailListWeb, :router

  import SimpleEmailListWeb.UserAuth
  alias SimpleEmailListWeb.Api.SignupController, as: ApiController

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SimpleEmailListWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :splash do
    plug :put_layout, {SimpleEmailListWeb.LayoutView, :splash}
  end

  pipeline :api do
    plug CORSPlug
    plug :accepts, ["json"]
  end

  scope "/api/v1" do
    pipe_through :api

    post "/signups/create", ApiController, :create
    options "/signups/create", ApiController, :options
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :splash]

    get "/", HomeController, :index
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :require_authenticated_user]

    resources "/lists/", ListController

    post "/lists/:list_id/keys", ListKeyController, :create
    delete "/lists/:list_id/keys/:id", ListKeyController, :delete
    get "/lists/:list_id/keys/:id", ListKeyController, :show

    get "/lists/:list_id/signups/:id/edit", SignupController, :edit
    get "/lists/:list_id/signups/new", SignupController, :new
    post "/lists/:list_id/signups", SignupController, :create
    patch "/lists/:list_id/signups/:id", SignupController, :update
    put "/lists/:list_id/signups/:id", SignupController, :update
    delete "/lists/:list_id/signups/:id", SignupController, :delete
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/simple_email_list_web/controllers/user_registration_controller.ex
defmodule SimpleEmailListWeb.UserRegistrationController do
  use SimpleEmailListWeb, :controller

  alias SimpleEmailList.Accounts
  alias SimpleEmailList.Accounts.User
  alias SimpleEmailListWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/simple_email_list_web/views/user_registration_view.ex
defmodule SimpleEmailListWeb.UserRegistrationView do
  use SimpleEmailListWeb, :view
end

lib/simple_email_list_web/templates/user_registration/new.html.heex
<div class="dark:bg-blue-900 px-6 py-8 my-10 shadow-xl ring-1 ring-gray-900/5 sm:max-w-lg sm:mx-auto sm:rounded-lg sm:px-10">
  <div class="max-w-lg mx-auto">

    <h1 class="text-3xl font-semibold mb-2 self-center text-center">Register</h1>

    <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <div class="">
        <%= email_input f, :email, required: true, class: "text-black w-full rounded ring-1 ring-blue-700 focus:ring-blue-500 my-1", placeholder: "Email" %>
        <%= error_tag f, :email %>
      </div>

      <div class="">
        <%= password_input f, :password, required: true, class: "text-black w-full rounded ring-1 ring-blue-700 focus:ring-blue-500 my-1", placeholder: "Password" %>
        <%= error_tag f, :password %>
      </div>

      <div>
        <%= submit "Register", class: "btn my-1 p-1 w-full rounded ring-1 ring-blue-500 bg-blue-700 text-white text-lg font-bold hover:bg-blue-500" %>
      </div>
    </.form>

    <div class="flex items-center justify-between my-1">
      <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "text-sm font-medium text-blue-700 dark:text-white dark:hover:text-blue-200 hover:text-blue-500" %>
      <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-sm font-medium text-blue-700 dark:text-white dark:hover:text-blue-200 hover:text-blue-500" %>
    </div>
  </div>
</div>