lib/simple_email_list_web/router.ex
defmodule SimpleEmailListWeb.Router do
  use SimpleEmailListWeb, :router

  import SimpleEmailListWeb.UserAuth
  alias SimpleEmailListWeb.Api.SignupController, as: ApiController

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SimpleEmailListWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :splash do
    plug :put_layout, {SimpleEmailListWeb.LayoutView, :splash}
  end

  pipeline :api do
    plug CORSPlug
    plug :accepts, ["json"]
  end

  scope "/api/v1" do
    pipe_through :api

    post "/signups/create", ApiController, :create
    options "/signups/create", ApiController, :options
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :splash]

    get "/", HomeController, :index
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :require_authenticated_user]

    resources "/lists/", ListController

    post "/lists/:list_id/keys", ListKeyController, :create
    delete "/lists/:list_id/keys/:id", ListKeyController, :delete
    get "/lists/:list_id/keys/:id", ListKeyController, :show

    get "/lists/:list_id/signups/:id/edit", SignupController, :edit
    get "/lists/:list_id/signups/new", SignupController, :new
    post "/lists/:list_id/signups", SignupController, :create
    patch "/lists/:list_id/signups/:id", SignupController, :update
    put "/lists/:list_id/signups/:id", SignupController, :update
    delete "/lists/:list_id/signups/:id", SignupController, :delete
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/simple_email_list/signups/list.ex
defmodule SimpleEmailList.Signups.List do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "lists" do
    field :name, :string

    # field :user_id, :binary_id
    belongs_to :user, SimpleEmailList.Accounts.User

    has_many :list_keys, SimpleEmailList.Signups.ListKey
    has_many :signups, SimpleEmailList.Signups.Signup

    timestamps()
  end

  @doc false
  def changeset(list, attrs) do
    list
    |> cast(attrs, [:name])
    |> validate_required([:name, :user_id])
    |> unique_constraint([:name, :user_id])
  end
end

lib/simple_email_list_web/controllers/list_controller.ex
defmodule SimpleEmailListWeb.ListController do
  use SimpleEmailListWeb, :controller

  alias SimpleEmailList.Signups
  alias SimpleEmailList.Signups.List
  alias SimpleEmailList.Signups.ListKey

  plug :authorize_action when action in [:show, :edit, :update, :delete]

  def index(conn, _params) do
    lists = Signups.list_lists(conn.assigns[:current_user])
    render(conn, "index.html", lists: lists)
  end

  def new(conn, _params) do
    changeset = Signups.change_list(%List{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"list" => list_params}) do
    case Signups.create_list(conn.assigns[:current_user], list_params) do
      {:ok, list} ->
        conn
        |> put_flash(:info, "List created successfully.")
        |> redirect(to: Routes.list_path(conn, :show, list))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    list = Signups.get_list!(id)
    list_keys = Signups.list_list_keys(id)
    signups = Signups.list_signups(id)
    changeset = Signups.change_list_key(%ListKey{})

    render(conn, "show.html",
      list: list,
      list_id: id,
      list_keys: list_keys,
      signups: signups,
      list_key_changeset: changeset
    )
  end

  def edit(conn, %{"id" => id}) do
    list = Signups.get_list!(id)
    changeset = Signups.change_list(list)
    render(conn, "edit.html", list: list, changeset: changeset)
  end

  def update(conn, %{"id" => id, "list" => list_params}) do
    list = Signups.get_list!(id)

    case Signups.update_list(list, list_params) do
      {:ok, list} ->
        conn
        |> put_flash(:info, "List updated successfully.")
        |> redirect(to: Routes.list_path(conn, :show, list))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", list: list, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    list = Signups.get_list!(id)
    {:ok, _list} = Signups.delete_list(list)

    conn
    |> put_flash(:info, "List deleted successfully.")
    |> redirect(to: Routes.list_path(conn, :index))
  end

  defp authorize_action(conn, _params) do
    list = Signups.get_list!(conn.params["id"])

    if list.user_id != conn.assigns[:current_user].id do
      conn
      |> put_flash(:error, "Unauthorized")
      |> redirect(to: Routes.list_path(conn, :index))
      |> halt()
    end

    conn
  end
end

lib/simple_email_list_web/views/list_view.ex
defmodule SimpleEmailListWeb.ListView do
  use SimpleEmailListWeb, :view
end

lib/simple_email_list_web/templates/list/edit.html.heex
<div class="flex my-4 pb-8">
    <%= link "Back", to: Routes.list_path(@conn, :index), class: "btn p-2 mr-2 md:px-6 md:mr-8 max-h-10" %>
    <h1 class="dark:text-white text-4xl font-bold md:pr-8">Edit Email List</h1>
</div>

<%= render "form.html", Map.put(assigns, :action, Routes.list_path(@conn, :update, @list)) %>

lib/simple_email_list_web/templates/list/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :name, class: "text-black w-full rounded ring-1 ring-blue-700 focus:ring-blue-500 my-1", placeholder: "Name" %>
  <%= error_tag f, :name %>

  <div class="">
    <%= submit "Save", class: "btn py-2 px-6 my-1" %>
  </div>
</.form>

lib/simple_email_list_web/templates/list/index.html.heex
<div class="flex my-4 pb-8">
  <h1 class="dark:text-white text-4xl font-bold pr-8">Email Lists</h1>
  <%= link ~H"New&nbsp;List", to: Routes.list_path(@conn, :new), class: "btn p-2 sm:px-6 bg-green-600 hover:bg-green-500 max-h-10" %>
</div>

<%= if Enum.empty?(@lists) do %>
  <div class="text-sm">
    <em>You have no lists, create a <%= link ~H"New&nbsp;List", to: Routes.list_path(@conn, :new), class: "rounded text-white p-1 bg-green-600 hover:bg-green-500" %> to get started.</em>
  </div>
<% else %>
  <table class="table-auto my-2 w-full">
    <thead class="text-sm font-light">
      <tr>
        <th class="text-left px-4">Name</th>

        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%= for list <- @lists do %>
      <tr class="odd:bg-sky-100 even:bg-slate-50 dark:odd:bg-slate-700 dark:even:bg-slate-600">
        <td class="md:pr-14 pl-4 h-16 w-[70%] align-middle text-left"><%= link list.name, to: Routes.list_path(@conn, :show, list), class: "dark:text-white text-blue-600 font-semibold text-lg hover:text-blue-500 hover:font-bold hover:text-xl" %></td>

        <td class="md:w-28">
          <%= link "Edit", to: Routes.list_path(@conn, :edit, list), class: "btn p-2 mr-1 md:px-6 md:mr-8 max-h-10" %>
        </td>
        <td class="md:w-28 md:pr-6">
          <%= link "Delete", to: Routes.list_path(@conn, :delete, list), method: :delete, data: [confirm: "Are you sure?"], class: "btn p-2 mr-1 md:px-6 bg-red-700 hover:bg-red-600" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

lib/simple_email_list_web/templates/list/new.html.heex
<div class="flex my-4 pb-8">
    <%= link "Back", to: Routes.list_path(@conn, :index), class: "btn p-2 mr-2 md:px-6 md:mr-8 max-h-10" %>
    <h1 class="dark:text-white text-4xl font-bold pr-8">New List</h1>
</div>

<%= render "form.html", Map.put(assigns, :action, Routes.list_path(@conn, :create)) %>

lib/simple_email_list_web/templates/list/show.html.heex
<div class="flex my-4 pb-8">
  <%= link "Back", to: Routes.list_path(@conn, :index), class: "btn p-2 mr-2 md:px-6 md:mr-8 max-h-10" %>
  <h1 class="dark:text-white text-4xl font-bold md:pr-8"><%= @list.name %></h1>
  <%= link "Edit", to: Routes.list_path(@conn, :edit, @list), class: "hidden md:block btn p-2 mr-2 md:px-6 md:mr-8 max-h-10" %>
</div>

<p id="alert-info" class="alert alert-info" role="alert"></p>

<div class="py-4">

  <h1 class="text-xl font-semibold">List Keys</h1>

  <table class="table-auto my-2 w-full">
    <thead class="text-sm font-light">
      <tr>
        <th class="text-left px-4">Client Code <span class="md:hidden">(Tap to copy)</span></th>

        <th class="hidden md:block"></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%= for list_key <- @list_keys do %>
      <tr class="odd:bg-sky-100 even:bg-slate-50 dark:odd:bg-slate-700 dark:even:bg-slate-600">
        <td class="md:pr-14 md:pl-4 h-10 align-middle">
          <span class="dark:ring-emerald-300 dark:bg-emerald-800 dark:text-emerald-200 rounded-xl ml-1 px-1 md:px-2 ring-2 ring-sky-400 text-teal-900 bg-sky-200 text-xs md:text-lg font-mono cursor-copy" 
                onclick={"copyAndNotify(`#{list_key.client_code}`, `#{list_key.client_code}`);"}><%= list_key.client_code %>
          </span>
        </td>

        <td class="hidden md:table-cell md:w-28">
          <span class="btn py-2 md:px-6 cursor-pointer" onclick={"copyAndNotify(`#{list_key.client_code}`, `#{list_key.client_code}`);"}>Copy</span>
        </td>
        <td class="hidden md:table-cell md:w-28 md:pr-6">
          <%= link "Code", to: Routes.list_key_path(@conn, :show, @list_id, list_key), method: :get, class: "btn p-2 mr-1 md:px-6" %>
        </td>
        <td class="md:w-28 md:pr-6">
          <%= link "Delete", to: Routes.list_key_path(@conn, :delete, @list_id, list_key), method: :delete, data: [confirm: "Are you sure?"], class: "btn p-2 mr-1 md:px-6 bg-red-700 hover:bg-red-600" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="py-2">
    <%= link "New List Key", to: Routes.list_key_path(@conn, :create, @list_id), method: :create, class: "btn py-2 px-6 bg-green-600 hover:bg-green-500" %>
  </div>
</div>

<div class="py-4">

  <h1 class="text-xl font-semibold">Signups</h1>

  <table class="table-auto my-2 w-full">
    <thead class="text-sm font-light">
      <tr>
        <th class="text-left px-4">Email</th>
        <th class="text-left px-4 hidden md:block">Name</th>

        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%= for signup <- @signups do %>
      <tr class="odd:bg-sky-100 even:bg-slate-50 dark:odd:bg-slate-700 dark:even:bg-slate-600">
        <td class="pr-14 pl-4 h-10 align-middle text-left">
          <a class="hover:text-blue-500 cursor-pointer text-lg" href={"mailto:#{signup.email}"}><%= signup.email %></a>
        </td>
        <td class="hidden md:table-cell pr-14 pl-4 h-10 align-middle text-left"><%= signup.name %></td>

        <td class="md:w-24">
          <%= link "Edit", to: Routes.signup_path(@conn, :edit, @list_id, signup), class: "btn p-2 mr-1 md:px-6 md:mr-8 max-h-10" %>
        </td>
        <td class="md:w-28 md:pr-6">
          <%= link "Delete", to: Routes.signup_path(@conn, :delete, @list_id, signup), method: :delete, data: [confirm: "Are you sure?"], class: "btn p-2 mr-1 md:px-6 bg-red-700 hover:bg-red-600" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="py-2">
    <%= link "New Signup", to: Routes.signup_path(@conn, :new, @list_id), class: "btn py-2 px-6 bg-green-600 hover:bg-green-500" %>
  </div>

</div>