lib/simple_email_list_web/router.ex
defmodule SimpleEmailListWeb.Router do
  use SimpleEmailListWeb, :router

  import SimpleEmailListWeb.UserAuth
  alias SimpleEmailListWeb.Api.SignupController, as: ApiController

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SimpleEmailListWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :splash do
    plug :put_layout, {SimpleEmailListWeb.LayoutView, :splash}
  end

  pipeline :api do
    plug CORSPlug
    plug :accepts, ["json"]
  end

  scope "/api/v1" do
    pipe_through :api

    post "/signups/create", ApiController, :create
    options "/signups/create", ApiController, :options
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :splash]

    get "/", HomeController, :index
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :require_authenticated_user]

    resources "/lists/", ListController

    post "/lists/:list_id/keys", ListKeyController, :create
    delete "/lists/:list_id/keys/:id", ListKeyController, :delete
    get "/lists/:list_id/keys/:id", ListKeyController, :show

    get "/lists/:list_id/signups/:id/edit", SignupController, :edit
    get "/lists/:list_id/signups/new", SignupController, :new
    post "/lists/:list_id/signups", SignupController, :create
    patch "/lists/:list_id/signups/:id", SignupController, :update
    put "/lists/:list_id/signups/:id", SignupController, :update
    delete "/lists/:list_id/signups/:id", SignupController, :delete
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SimpleEmailListWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/simple_email_list_web/views/layout_view.ex
defmodule SimpleEmailListWeb.LayoutView do
  use SimpleEmailListWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/simple_email_list_web/templates/layout/_user_menu.html.heex
<div class="w-full bg-blue-900  flex items-center justify-between md:fixed top-0">

  <a href="/" class="p-2 flex bg-gradient-to-r from-rose-700 to-blue-900 h-full">
    <img class="hidden md:block sm:h-12" src={Routes.static_path(@conn, "/images/logo.png")} alt="Simple Email List Logo"/>
    <h1 class="text-2xl md:text-3xl lg:text-4xl text-white pl-2 sm:py-1">Simple Email List</h1>
  </a>
  <div class="flex">
    <div id="theme-options" class="flex rounded text-white font-bold md:mr-3 ring-2 ring-blue-500">
        <button id="theme-option-light" type="button" title="Light Theme"
            class="cursor-pointer w-1/3 p-1 sm:px-2.5 hover:bg-blue-500 text-center rounded-l">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd"
                    d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
                    clip-rule="evenodd" />
            </svg>
        </button>
        <button id="theme-option-dark" type="button" title="Dark Theme"
            class="cursor-pointer w-1/3 p-1 sm:px-2.5 hover:bg-blue-500 text-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" />
            </svg>
        </button>
        <button id="theme-option-system" type="button" title="System Theme"
            class="cursor-pointer w-1/3 p-1 sm:px-2.5 hover:bg-blue-500 text-center rounded-r">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd"
                    d="M3 5a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2h-2.22l.123.489.804.804A1 1 0 0113 18H7a1 1 0 01-.707-1.707l.804-.804L7.22 15H5a2 2 0 01-2-2V5zm5.771 7H5V5h10v7H8.771z"
                    clip-rule="evenodd" />
            </svg>
        </button>
    </div>

    <div class="hidden md:flex">
      <%= if @current_user do %>
        <%= link ~H"My&nbsp;Lists", to: Routes.list_path(@conn, :index), class: "px-3 py-2 mr-3 ring-2 ring-blue-500 rounded bg-blue-700 hover:bg-blue-500 text-white font-bold" %>
      <% end %>
      <%= if @current_user do %>
        <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "px-3 py-2 mr-3 ring-2 ring-blue-500 rounded bg-blue-700 hover:bg-blue-500 text-white font-bold" %>
        <%= link ~H"Log&nbsp;out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "px-3 py-2 mr-3 ring-2 ring-blue-500 rounded bg-blue-700 hover:bg-blue-500 text-white font-bold" %>
      <% else %>
        <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "px-3 py-2 mr-3 ring-2 ring-blue-500 rounded bg-blue-700 hover:bg-blue-500 text-white font-bold" %>
        <%= link ~H"Log&nbsp;in", to: Routes.user_session_path(@conn, :new), class: "px-3 py-2 mr-3 ring-2 ring-blue-500 rounded bg-blue-700 hover:bg-blue-500 text-white font-bold" %>
      <% end %>
    </div>
    <div id="mobile-menu-toggle" class="md:hidden mx-3 my-1 space-y-2">
      <span class="block w-8 h-0.5 bg-white rounded-lg"></span>
      <span class="block w-8 h-0.5 bg-white rounded-lg"></span>
      <span class="block w-8 h-0.5 bg-white rounded-lg"></span>
    </div>
  </div>

</div>

<div id="mobile-menu" class="hidden">
  <%= if @current_user do %>
    <div class="w-full border-b-2 border-blue-500">
      <%= link ~H"My&nbsp;Lists", to: Routes.list_path(@conn, :index), class: "w-full block py-3 bg-blue-700 hover:bg-blue-500 text-white text-2xl text-center font-bold" %>
    </div>
    <div class="w-full border-b-2 border-blue-500">
      <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "w-full block py-3 bg-blue-700 hover:bg-blue-500 text-white text-2xl text-center font-bold" %>
    </div>
    <div class="w-full border-b-2 border-blue-500">
      <%= link ~H"Log&nbsp;out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "w-full block py-3 bg-blue-700 hover:bg-blue-500 text-white text-2xl text-center font-bold" %>
    </div>
  <% else %>
    <div class="w-full border-b-2 border-blue-500">
      <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "w-full block py-3 bg-blue-700 hover:bg-blue-500 text-white text-2xl text-center font-bold" %>
    </div>
    <div class="w-full border-b-2 border-blue-500">
      <%= link ~H"Log&nbsp;in", to: Routes.user_session_path(@conn, :new), class: "w-full block py-3 bg-blue-700 hover:bg-blue-500 text-white text-2xl text-center font-bold" %>
    </div>
  <% end %>
</div>

lib/simple_email_list_web/templates/layout/app.html.heex
<main class="p-2 my-1 md:py-8 md:my-10 sm:max-w-5xl sm:mx-auto md:px-10">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/simple_email_list_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/simple_email_list_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Simple Email List" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="dark:bg-slate-800 dark:text-white">
    <script>
      // Copy a value to the clipboard and show a notification.
      function copyAndNotify(value, conf_value) {
          alertElem = document.getElementById("alert-info");
          // Copy the value to clipboard.
          navigator.clipboard.writeText(value);
          // Notify the user.
          alertElem.innerHTML = `Copied ${conf_value} to clipboard.`;
      }
    </script>
    <header>
      <section class="">
        <nav>
          <%= render "_user_menu.html", assigns %>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/simple_email_list_web/templates/layout/splash.html.heex
<main class="bg-gradient-to-b w-full min-h-screen h-full from-blue-400 dark:from-slate-900 to-slate-200 dark:to-blue-900">
  <p class="alert alert-info relative top-20 sm:max-w-5xl sm:mx-auto md:px-10" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger relative top-20 sm:max-w-5xl sm:mx-auto md:px-10" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>